# version: '3.8'

# services:
#     app:
#       build: .
#       container_name: user_project
#       ports:
#         - "3000:3000"
#       env_file:
#         - .env
#       command: ["sh","-c","npx prisma migrate dev && node dist/index.js"]


# Locally 

version: '3.8'

services:
    postgres:
      image: postgres
      ports:
        - "5432:5432"
    app:
      build:
        context: ./
        dockerfile: Dockerfile
      container_name: user_project
      restart: unless-stopped
      environment:
        - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
      ports:
        - "3000:3000"
      depends_on:
        - postgres